on:
  push:
    branches:
    - main
    - release/*
jobs:
  docker_frontend:
    name: docker front-end
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Log into registry
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.ACR_ENDPOINT }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - name: Build & Push
          uses: docker/build-push-action@v3
          with:
            context: ./front-end
            push: true
            tags: ${{ secrets.ACR_ENDPOINT }}/frontend:latest
  docker_backend:
    name: docker back-end
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Log into registry
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.ACR_ENDPOINT }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - name: Build & Push
          uses: docker/build-push-action@v3
          with:
            context: ./back-end
            push: true
            tags: ${{ secrets.ACR_ENDPOINT }}/backend:latest
  restart:
    name: restart
    runs-on: ubuntu-18.04
    needs: [docker_frontend, docker_backend]
    steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - run: |
            az resource list --name kinder-tracker
