on:
  push:
    branches:
    - main
    - release/*
jobs:
  initialize:
    name: initialize
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - name: init
          run: |
            ls -la
  build_frontend:
    name: build front-end
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - name: yarn install, build and test
          run: |
            cd front-end
            yarn install
            yarn run build --if-present
  docker_frontend:
    name: docker front-end
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - name: docker frontend
          run: |
            cd front-end
            docker build . --tag kindertracker/frontend
  build_backend:
    name: build back-end
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - name: yarn install, build and test
          run: |
            cd back-end
            
